In [ ]:

import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import time

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import svm
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
import sklearn 

In [ ]:
!wget https://raw.githubusercontent.com/lee1613/Sentiment-Analysis-NLP-/main/dataset.csv

--2023-04-02 06:05:35--  https://raw.githubusercontent.com/lee1613/Sentiment-Analysis-NLP-/main/dataset.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1273144 (1.2M) [text/plain]
Saving to: ‘dataset.csv’

dataset.csv         100%[===================>]   1.21M  --.-KB/s    in 0.04s   

2023-04-02 06:05:35 (27.5 MB/s) - ‘dataset.csv’ saved [1273144/1273144]



In [ ]:
df  = pd.read_csv("dataset.csv", header = None)
df.rename(columns = {0:"Label",1:"Sentiment"}, inplace = True)
print(df.shape)
df.head(10)


(10662, 2)


Label                                          Sentiment
0      1  the rock is destined to be the 21st century's ...
1      1  the gorgeously elaborate continuation of " the...
2      1                     effective but too-tepid biopic
3      1  if you sometimes like to go to the movies to h...
4      1  emerges as something rare , an issue movie tha...
5      1  the film provides some great insight into the ...
6      1  offers that rare combination of entertainment ...
7      1  perhaps no picture ever made has more literall...
8      1  steers turns in a snappy screenplay that curls...
9      1  take care of my cat offers a refreshingly diff...

In [ ]:
vectorizer = TfidfVectorizer(min_df = 5, max_df = .8,sublinear_tf = True,use_idf = True)
vectorizer.fit_transform(df.loc[:,"Sentiment"])
vector = vectorizer.transform(df.loc[:,"Sentiment"])
print (vector)

  (0, 4328)	0.26110675107799397
  (0, 4126)	0.12370595269480736
  (0, 4055)	0.09000886682954677
  (0, 4054)	0.08549469961952712
  (0, 4051)	0.12944511001387746
  (0, 3823)	0.24127897757382433
  (0, 3774)	0.29008138745794615
  (0, 3450)	0.27261292991290054
  (0, 3352)	0.2252064900917602
  (0, 2813)	0.1391790519921295
  (0, 2705)	0.16882810602592976
  (0, 2442)	0.15927930915168467
  (0, 2173)	0.27261292991290054
  (0, 2145)	0.078010900515246
  (0, 1861)	0.15903150721358722
  (0, 1775)	0.28024366234140663
  (0, 1744)	0.19747550050369891
  (0, 1355)	0.14786206799452506
  (0, 1049)	0.27621589266391555
  (0, 598)	0.2399377657576403
  (0, 331)	0.1190787948325743
  (0, 229)	0.2565404424308364
  (0, 175)	0.06037654079972127
  (0, 13)	0.2848099709885641
  (1, 4543)	0.19462412943574495
  :	:
  (10659, 1582)	0.1924045887185008
  (10659, 1050)	0.27398221995603944
  (10659, 742)	0.2646904767305713
  (10659, 722)	0.26900336074948833
  (10659, 544)	0.27398221995603944
  (10659, 301)	0.2266215088449988

In [ ]:
print(vector.toarray()[2])
print(df.loc[2,"Sentiment"])

[0. 0. 0. ... 0. 0. 0.]
effective but too-tepid biopic


In [ ]:
print(len(vectorizer.vocabulary_))
#print(vectorizer.vocabulary_)
print(vector.shape)
print(vector[1,].shape) ## Indicates that each vector has a vector length of 4574 to represent it, which is the length
# of the vocabulary 
print((vector[1].toarray()[0]))
print(len(vector[1].toarray()[0]))


4574
(10662, 4574)
(1, 4574)
[0. 0. 0. ... 0. 0. 0.]
4574


In [ ]:
train_x, test_x, train_y, test_y = train_test_split(vector,df.loc[:,"Label"],train_size = .8)
print((train_x.shape,test_x.shape, train_y.shape, test_y.shape))

((8529, 4574), (2133, 4574), (8529,), (2133,))


In [ ]:
from sklearn.naive_bayes import MultinomialNB
naive_bayes=MultinomialNB()
naive_bayes.fit(train_x, train_y)
prediction=naive_bayes.predict(test_x)
print(prediction)

[0 0 0 ... 0 0 1]


In [ ]:
report = classification_report(test_y, prediction, output_dict = True)
print(report)

{'0': {'precision': 0.7533274179236912, 'recall': 0.7897674418604651, 'f1-score': 0.771117166212534, 'support': 1075}, '1': {'precision': 0.7753479125248509, 'recall': 0.7372400756143668, 'f1-score': 0.7558139534883721, 'support': 1058}, 'accuracy': 0.7637130801687764, 'macro avg': {'precision': 0.764337665224271, 'recall': 0.7635037587374159, 'f1-score': 0.7634655598504531, 'support': 2133}, 'weighted avg': {'precision': 0.7642499136049041, 'recall': 0.7637130801687764, 'f1-score': 0.7635265431172863, 'support': 2133}}


In [ ]:
accuracy=sklearn.metrics.accuracy_score(test_y,prediction)
print(accuracy)

0.7637130801687764
